[package]
name = "redirust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[libs]
path = "src/lib.rs"

[[bin]]
name = "redirust"

[dependencies]
